services:
  - type: web
    name: ai-hrms-server
    env: node
    plan: free
    repoPath: .
    branch: main
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: "3000"

  - type: static
    name: ai-hrms-client
    env: static
    plan: free
    repoPath: .
    branch: main
    buildCommand: cd client && npm install && npm run build
    publishPath: client/dist
